### ISSUE TITLE
Trouble handling indented options

### ISSUE THREAD

**Issue by Yarakundapp** [louib/confirm#45]
For all processing that includes a configuration file, there seems to be an issue with options that are indented.

For example : 

>[global]
>base_path = ~/MYPATH

Would work.

>[global]
>&nbsp;base_path = ~/MYPATH

Would trigger a parsing error. Since I believe the later is still a valid configuration, it might be best to see if a fix is possible (or at least mention this limitation)

**Comment by Ronan-** [comment]
Something to help not clarify the issue : https://en.wikipedia.org/wiki/INI_file#Whitespace

**Comment by Ronan-** [comment]
More info : this might work on python 3 but not python 2.

Comparing https://docs.python.org/3/library/configparser.html#supported-ini-file-structure with https://docs.python.org/2/library/configparser.html , the latter makes no mention of whitespace before/around keys.

Could you test with python 3 @Yarakundapp ?

**Comment by Yarakundapp** [comment]
@Ronan- The file does seem to be parsing correctly on a Python 3 environment (3.4.0) with confirm installed.

**Comment by Ronan-** [comment]
Tagging as wontfix, this is a python 2 ConfigParser issue which we can't really do anything about.
